# Site settings - Optimized for performance
title: "Hidden Crucials"
description: "A field guide to the patterns that shape digital-age existence"
url: "https://farkhanmaul.github.io"
baseurl: "/hidden-crucials"
author: "Farkhan Maul"

# Build settings - Performance optimized
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Jakarta

# Performance settings
incremental: true
strict_front_matter: false
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Kramdown settings for performance
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
    span:
      line_numbers: false

# Sass settings for CSS optimization
sass:
  style: compressed
  sourcemap: never

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "docs"
      author: "Hidden Crucials"
  - scope:
      path: ""
    values:
      layout: "docs"

# Exclude from processing - Performance optimization
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/css/docs.css
  - assets/js/docs.js
  - README.md
  - LICENSE
  - "*.log"

# Include critical files
include:
  - sw.js
  - _redirects

# HTML compression for production
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]